services:
  ros2_jazzy_cpu:
    build: .
    image: var_ros2_image
    container_name: var_container
    environment:
      - DISPLAY=:${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws:/home/ros2_ws/src
    privileged: true
    stdin_open: true
    tty: true

    # BLOQUE PARA ACTIVAR LA GPU
  #  deploy:
  #    resources:
  #      reservations:
  #        devices:
  #          - driver: nvidia
  #            count: all      
  #            capabilities: [gpu]

    command: sh -c "chown -R 1000:1000 /home/ros2_ws/src && bash"
    # Dar permisos de escritura al usuario no root (1000) desde fuera del contenedor en el volumen montado
