services:
  ros2_jazzy_cpu:
    build: .
    platform: linux/arm64
    image: var_ros2_image_cpu
    container_name: var_container_cpu
    ports:
      - "5900:5900"        # puerto VNC
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - TURTLEBOT3_MODEL=waffle
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GL_VERSION_OVERRIDE=3.3
      - MESA_GLSL_VERSION_OVERRIDE=330
    volumes:
      - ./src:/home/ros2_ws/src
    privileged: true
    stdin_open: true
    tty: true
    command: sh -c "
      mkdir -p /tmp/runtime-root && chmod 700 /tmp/runtime-root &&
      chown -R 1000:1000 /home/ros2_ws/src 2>/dev/null || true &&
      Xvfb :0 -screen 0 1920x1080x24 &
      sleep 5 &&
      eval $(dbus-launch --sh-syntax) &&
      env DISPLAY=:0 startxfce4 &
      sleep 5 &&
      x11vnc -display :0 -passwd davidet -forever -shared -bg &&
      bash"