services:
  ros2_jazzy_cpu:
    build: .
    platform: linux/arm64
    image: var_ros2_image
    container_name: var_container
    ports:
      - "5900:5900"        # puerto VNC
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - TURTLEBOT3_MODEL=waffle
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GL_VERSION_OVERRIDE=3.3
      - MESA_GLSL_VERSION_OVERRIDE=330
    volumes:
      - ./src:/home/ros2_ws/src
    privileged: true
    stdin_open: true
    tty: true

    # BLOQUE PARA ACTIVAR LA GPU
  #  deploy:
  #    resources:
  #      reservations:
  #        devices:
  #          - driver: nvidia
  #            count: all      
  #            capabilities: [gpu]

    command: sh -c "chown -R 1000:1000 /home/ros2_ws/src && bash"
    # Dar permisos de escritura al usuario no root (1000) desde fuera del contenedor en el volumen montado
